# Generated by Django 4.2.3 on 2023-07-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=25, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Two', 'Two wheelers'), ('Three', 'Three wheelers'), ('Four', 'Four wheelers')], max_length=50)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_description', models.TextField()),
            ],
        ),
    ]
